disable-version-string: true
with-expecter: true
inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "mock{{.InterfaceName|firstUpper}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}_test.go"
all: true
packages:
  github.com/ministryofjustice/opg-data-lpa-store/internal/ddb:
  github.com/ministryofjustice/opg-data-lpa-store/internal/event:
  github.com/ministryofjustice/opg-data-lpa-store/internal/objectstore:
  github.com/ministryofjustice/opg-data-lpa-store/internal/shared:
  github.com/ministryofjustice/opg-data-lpa-store/lambda/create:
  github.com/ministryofjustice/opg-data-lpa-store/lambda/get:
  github.com/ministryofjustice/opg-data-lpa-store/lambda/getlist:
