all: true
dir: "{{.InterfaceDir}}"
structname: mock{{.InterfaceName|firstUpper}}
pkgname: "{{.SrcPackageName}}"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/ministryofjustice/opg-data-lpa-store/internal/ddb: {}
  github.com/ministryofjustice/opg-data-lpa-store/internal/event: {}
  github.com/ministryofjustice/opg-data-lpa-store/internal/objectstore: {}
  github.com/ministryofjustice/opg-data-lpa-store/internal/shared: {}
  github.com/ministryofjustice/opg-data-lpa-store/lambda/create: {}
  github.com/ministryofjustice/opg-data-lpa-store/lambda/get: {}
  github.com/ministryofjustice/opg-data-lpa-store/lambda/getlist: {}
  github.com/ministryofjustice/opg-data-lpa-store/lambda/update: {}
  github.com/ministryofjustice/opg-data-lpa-store/lambda/getupdates: {}
