// Code generated by mockery v2.42.2. DO NOT EDIT.

package main

import (
	context "context"

	shared "github.com/ministryofjustice/opg-data-lpa-store/internal/shared"
	mock "github.com/stretchr/testify/mock"
)

// mockStore is an autogenerated mock type for the Store type
type mockStore struct {
	mock.Mock
}

type mockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockStore) EXPECT() *mockStore_Expecter {
	return &mockStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, uid
func (_m *mockStore) Get(ctx context.Context, uid string) (shared.Lpa, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 shared.Lpa
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (shared.Lpa, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) shared.Lpa); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Get(0).(shared.Lpa)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *mockStore_Expecter) Get(ctx interface{}, uid interface{}) *mockStore_Get_Call {
	return &mockStore_Get_Call{Call: _e.mock.On("Get", ctx, uid)}
}

func (_c *mockStore_Get_Call) Run(run func(ctx context.Context, uid string)) *mockStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockStore_Get_Call) Return(_a0 shared.Lpa, _a1 error) *mockStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockStore_Get_Call) RunAndReturn(run func(context.Context, string) (shared.Lpa, error)) *mockStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, data
func (_m *mockStore) Put(ctx context.Context, data interface{}) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type mockStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - data interface{}
func (_e *mockStore_Expecter) Put(ctx interface{}, data interface{}) *mockStore_Put_Call {
	return &mockStore_Put_Call{Call: _e.mock.On("Put", ctx, data)}
}

func (_c *mockStore_Put_Call) Run(run func(ctx context.Context, data interface{})) *mockStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *mockStore_Put_Call) Return(_a0 error) *mockStore_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockStore_Put_Call) RunAndReturn(run func(context.Context, interface{}) error) *mockStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// newMockStore creates a new instance of mockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStore {
	mock := &mockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
