// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package event

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/eventbridge"
	mock "github.com/stretchr/testify/mock"
)

// newMockEventBridgeClient creates a new instance of mockEventBridgeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEventBridgeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEventBridgeClient {
	mock := &mockEventBridgeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockEventBridgeClient is an autogenerated mock type for the EventBridgeClient type
type mockEventBridgeClient struct {
	mock.Mock
}

type mockEventBridgeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEventBridgeClient) EXPECT() *mockEventBridgeClient_Expecter {
	return &mockEventBridgeClient_Expecter{mock: &_m.Mock}
}

// PutEvents provides a mock function for the type mockEventBridgeClient
func (_mock *mockEventBridgeClient) PutEvents(ctx context.Context, params *eventbridge.PutEventsInput, optFns ...func(*eventbridge.Options)) (*eventbridge.PutEventsOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutEvents")
	}

	var r0 *eventbridge.PutEventsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *eventbridge.PutEventsInput, []func(*eventbridge.Options)) (*eventbridge.PutEventsOutput, error)); ok {
		return returnFunc(ctx, params, optFns)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *eventbridge.PutEventsInput, ...func(*eventbridge.Options)) *eventbridge.PutEventsOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eventbridge.PutEventsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *eventbridge.PutEventsInput, ...func(*eventbridge.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockEventBridgeClient_PutEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutEvents'
type mockEventBridgeClient_PutEvents_Call struct {
	*mock.Call
}

// PutEvents is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *mockEventBridgeClient_Expecter) PutEvents(ctx interface{}, params interface{}, optFns ...interface{}) *mockEventBridgeClient_PutEvents_Call {
	return &mockEventBridgeClient_PutEvents_Call{Call: _e.mock.On("PutEvents",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mockEventBridgeClient_PutEvents_Call) Run(run func(ctx context.Context, params *eventbridge.PutEventsInput, optFns ...func(*eventbridge.Options))) *mockEventBridgeClient_PutEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*eventbridge.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*eventbridge.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*eventbridge.PutEventsInput), variadicArgs...)
	})
	return _c
}

func (_c *mockEventBridgeClient_PutEvents_Call) Return(putEventsOutput *eventbridge.PutEventsOutput, err error) *mockEventBridgeClient_PutEvents_Call {
	_c.Call.Return(putEventsOutput, err)
	return _c
}

func (_c *mockEventBridgeClient_PutEvents_Call) RunAndReturn(run func(ctx context.Context, params *eventbridge.PutEventsInput, optFns ...func(*eventbridge.Options)) (*eventbridge.PutEventsOutput, error)) *mockEventBridgeClient_PutEvents_Call {
	_c.Call.Return(run)
	return _c
}
