// Code generated by mockery. DO NOT EDIT.

package objectstore

import (
	context "context"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// mockAwsS3Client is an autogenerated mock type for the awsS3Client type
type mockAwsS3Client struct {
	mock.Mock
}

type mockAwsS3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAwsS3Client) EXPECT() *mockAwsS3Client_Expecter {
	return &mockAwsS3Client_Expecter{mock: &_m.Mock}
}

// PutObject provides a mock function with given fields: ctx, input, opts
func (_m *mockAwsS3Client) PutObject(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, input)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return rf(ctx, input, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = rf(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = rf(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAwsS3Client_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type mockAwsS3Client_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.PutObjectInput
//   - opts ...func(*s3.Options)
func (_e *mockAwsS3Client_Expecter) PutObject(ctx interface{}, input interface{}, opts ...interface{}) *mockAwsS3Client_PutObject_Call {
	return &mockAwsS3Client_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *mockAwsS3Client_PutObject_Call) Run(run func(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options))) *mockAwsS3Client_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*s3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*s3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*s3.PutObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *mockAwsS3Client_PutObject_Call) Return(_a0 *s3.PutObjectOutput, _a1 error) *mockAwsS3Client_PutObject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAwsS3Client_PutObject_Call) RunAndReturn(run func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *mockAwsS3Client_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAwsS3Client creates a new instance of mockAwsS3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAwsS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAwsS3Client {
	mock := &mockAwsS3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
