// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package objectstore

import (
	"context"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// newMockAwsS3Client creates a new instance of mockAwsS3Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAwsS3Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAwsS3Client {
	mock := &mockAwsS3Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockAwsS3Client is an autogenerated mock type for the awsS3Client type
type mockAwsS3Client struct {
	mock.Mock
}

type mockAwsS3Client_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAwsS3Client) EXPECT() *mockAwsS3Client_Expecter {
	return &mockAwsS3Client_Expecter{mock: &_m.Mock}
}

// PutObject provides a mock function for the type mockAwsS3Client
func (_mock *mockAwsS3Client) PutObject(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, []func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return returnFunc(ctx, input, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockAwsS3Client_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type mockAwsS3Client_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx
//   - input
//   - opts
func (_e *mockAwsS3Client_Expecter) PutObject(ctx interface{}, input interface{}, opts ...interface{}) *mockAwsS3Client_PutObject_Call {
	return &mockAwsS3Client_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *mockAwsS3Client_PutObject_Call) Run(run func(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options))) *mockAwsS3Client_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*s3.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*s3.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*s3.PutObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *mockAwsS3Client_PutObject_Call) Return(putObjectOutput *s3.PutObjectOutput, err error) *mockAwsS3Client_PutObject_Call {
	_c.Call.Return(putObjectOutput, err)
	return _c
}

func (_c *mockAwsS3Client_PutObject_Call) RunAndReturn(run func(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *mockAwsS3Client_PutObject_Call {
	_c.Call.Return(run)
	return _c
}

// newMockPresignClient creates a new instance of mockPresignClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPresignClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPresignClient {
	mock := &mockPresignClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPresignClient is an autogenerated mock type for the presignClient type
type mockPresignClient struct {
	mock.Mock
}

type mockPresignClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPresignClient) EXPECT() *mockPresignClient_Expecter {
	return &mockPresignClient_Expecter{mock: &_m.Mock}
}

// PresignGetObject provides a mock function for the type mockPresignClient
func (_mock *mockPresignClient) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PresignGetObject")
	}

	var r0 *v4.PresignedHTTPRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, []func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)); ok {
		return returnFunc(ctx, params, optFns)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) *v4.PresignedHTTPRequest); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v4.PresignedHTTPRequest)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.PresignOptions)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPresignClient_PresignGetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetObject'
type mockPresignClient_PresignGetObject_Call struct {
	*mock.Call
}

// PresignGetObject is a helper method to define mock.On call
//   - ctx
//   - params
//   - optFns
func (_e *mockPresignClient_Expecter) PresignGetObject(ctx interface{}, params interface{}, optFns ...interface{}) *mockPresignClient_PresignGetObject_Call {
	return &mockPresignClient_PresignGetObject_Call{Call: _e.mock.On("PresignGetObject",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mockPresignClient_PresignGetObject_Call) Run(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions))) *mockPresignClient_PresignGetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*s3.PresignOptions), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*s3.PresignOptions))
			}
		}
		run(args[0].(context.Context), args[1].(*s3.GetObjectInput), variadicArgs...)
	})
	return _c
}

func (_c *mockPresignClient_PresignGetObject_Call) Return(presignedHTTPRequest *v4.PresignedHTTPRequest, err error) *mockPresignClient_PresignGetObject_Call {
	_c.Call.Return(presignedHTTPRequest, err)
	return _c
}

func (_c *mockPresignClient_PresignGetObject_Call) RunAndReturn(run func(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error)) *mockPresignClient_PresignGetObject_Call {
	_c.Call.Return(run)
	return _c
}
